### ISSUE TITLE
add voice output

### ISSUE THREAD

**Issue by silberzwiebel** [scoute-dich/Sieben#10]
Hi,

thanks for this app!
It would be great, if the app had a voice output, either artificial (text-to-speech), or natural language (i.e., just play pre-recorded files.)
With this you would not not have to look at your phone to see
- what to do next
- when the time for the exercise is finished

Thanks, 
silberzwiebel

**Comment by scoute-dich** [comment]
When time is finished the app should play a notification sound. It's very silent.

But the idea sounds good. Let's see when I have more time...

**Comment by scoute-dich** [comment]
O found a solution will be in next update.

**Comment by scoute-dich** [comment]
v1.5 is on his way

**Comment by cipo7741** [comment]
It's true, looking on the phone might be tedious but I liked the "bing". After a while you remember what comes next and only want to hear when the time is up. Now it's someone giving commands.

**Comment by silberzwiebel** [comment]
Thanks, works great. Maybe you could add a setting that allows to turn off voice and instead uses only the "bing"? Then everybody is happy ;)

**Comment by scoute-dich** [comment]
Will ad settings to enable/disable tts/beep.

**Comment by scoute-dich** [comment]
Done.

**Comment by cipo7741** [comment]
Thank you!
Also love how you solved #12.
