### ISSUE TITLE
exercise enhancement

### ISSUE THREAD

**Issue by beli3ver** [scoute-dich/Sieben#12]
It would be really helpful when you make a 3 seconds break after 15 seconds in the side plank exercise.
So you can switch sites.

Maybe also a text in the bottom that say to you to turn sites.

**Comment by cipo7741** [comment]
That would be nice. I just count slowly till 10, than turn and do the same on the other side. It's the last exercise, so it's fine doing it a little longer.

**Comment by silberzwiebel** [comment]
I repeat the whole last exercise, i.e., 30 seconds one side, 30 seconds other side. I used a different app before and thought this is the way to do? If so, the side plank exercise needs to be in this app twice.

**Comment by scoute-dich** [comment]
Done. I splited the exercise in two parts with a 5 seconds break.
