### ISSUE TITLE
build folder should not be tracked by git

### ISSUE THREAD

**Issue by cippaciong** [scoute-dich/Sieben#13]
Hi, your git repository should include only code (and other resources like graphics or anything else you app needs) and not the build folders or the editor specific folders.
Right now the zip file of you latest release is ~100MB which is **huge!**
I suggest you to google *"gitignore android studio"* or something similar to better understand why and how you should do this. :smiley:

**Comment by scoute-dich** [comment]
Thanks for the hint. As said I'm new in developing. I think I solved the problem. Also out was good that you said "google it" and not gave me a step by step tutorial. I'm willingly to learn..

Of there are further problems, please tell me.
