### ISSUE TITLE
APK is 4x bigger after moving images out of drawable folder 

### ISSUE THREAD

**Issue by cippaciong** [scoute-dich/Sieben#14]
Hello, version 1.5 is almost four times bigger compared to 1.4 (21,3MB vs 5,4MB). This is mainly caused by the fact that you moved the exercise pictures out of drawable and are now duplicated in each mipmap folder.
I don't know precisely what are the suggested standards for Android applications regarding images location but I think that using those directories is useful only if you need different images size for different display resolutions. In this way each directory contains exactly the same files increasing the apk size without any actual benefit.
As I said I don't what is the best practice for Android but I feel like it would be better if you move those images back to the drawable folder or anywhere resolution independent images should reside.

**Comment by scoute-dich** [comment]
If I use an resolution independent folder to store the pictures, the app crashes after some time. 

I researched a little bit. Now I put the pictures in different drawable folders, but with different resolutions. That seems to work. The actual apk size is now about 8 mb.
