### ISSUE TITLE
Change duration of exercices

### ISSUE THREAD

**Issue by jinformatique** [scoute-dich/Sieben#19]
Hi, I love your app and the minimal approach and the fact it's FOSS! It's great.

Just wanted to know if it would be possible to add an option in the settings to change the duration of the exercices.
Instead of having 30 secondes, I would be able to change it to 45 secondes or 60 secondes.
That would be awesome.

**Comment by scoute-dich** [comment]
I think that would be possible, but next week school starts again (I'm working as teacher), so I don't think that I have the time in the next weeks...

**Comment by jinformatique** [comment]
Sure, I hope than whenever you'll find the time, you or another android dev could propose a pull request.

**Comment by scoute-dich** [comment]
Hey, I found some time, Update will be there in the next days. ;-)

**Comment by jinformatique** [comment]
Many thanks!! It's great you were able to add it so quickly.

**Comment by scoute-dich** [comment]
; -)
