### ISSUE TITLE
Use English as default locale

### ISSUE THREAD

**Issue by martykan** [scoute-dich/Sieben#2]
Right now, when you are using an unsupported locale (Spanish, French, Chinese, etc.), everything is in German by default.

**Comment by scoute-dich** [comment]
Do know how to set English as default language? Otherwise I have to research it...

**Comment by scoute-dich** [comment]
Hi,

just copied the strings from German to English and vice versa. I've tested it on my device with French and it's working. Thanks for the tip. I'm new in developing apps...

Regads
scoute-dich

**Comment by martykan** [comment]
Great, thanks!
