### ISSUE TITLE
Jumping Over Exercise Number Two

### ISSUE THREAD

**Issue by YoungNFoolish** [scoute-dich/Sieben#21]
Hello Gaukler,
I got a Huawei Honor 4c running Android version 6 and installed the app from f-droid. Then i opened the app, swiped up and started the exercises. After exercise number one and a short break, it jumps over exercise number two and started exercise number three!
FYI, all the exercises are selected in settings activity.
So, what's the matter?!

sorry for my bad english :sweat_smile:

**Comment by scoute-dich** [comment]
Sorry for my late response. I can confirm this. I will fix this in the next update. Thanks for the report.

**Comment by scoute-dich** [comment]
I found the mistake. It is fixed. Update on his way. Thanks again. ;-)
