### ISSUE TITLE
Allow user to add exercices

### ISSUE THREAD

**Issue by mdouchin** [scoute-dich/Sieben#24]
I would like to know it here is an easy way to add some exercices. Are they stored in some file ?
The best would be to have 
- a CSV file with title, description, image name, default duration
- a system to read this csv file and create exercices
- show images stored relatively from the csv file

This would let your tool
- be easily customisable
- have people contributing to the list of exercices very easily

For example

| title | description | body_parts | category | image | default_duration |
| :-: | --- | --- | --- | --- | --- |
| Stretch neck | Let your head drop on one side. Stay 5 seconds. Move to the other side. Stay 5 secondes | neck, shoulder | stretching | my-neck-stretching-exercice.png | 120 |
| Superman | On your knees, hands on the ground, rise one leg and the opposite arm, stretch, keep 10 seconds, and reverse side | abs, back | stretching, reinforcement | my-superman-image.jpg | 60 |

**Comment by scoute-dich** [comment]
I will not implement this.

The exercises are not stored in a file. There are separate activities for each. I do not know how to load exercises from a csv file... 

The goal is to keep the app as simple as possible.
