### ISSUE TITLE
Phone locks while working out

### ISSUE THREAD

**Issue by MAWSpitau** [scoute-dich/Sieben#3]
Hey there,

I tried the app and it is great, easy and simple! But my phone turns black while I was working on myself. So maybe it would be great to not let the phone turn off, while the app is working. 

Greetings MAW

**Comment by scoute-dich** [comment]
Hi,

no problem is already fixed and will be implemented on version 1.3 (probably next weekend).

**Comment by scoute-dich** [comment]
Update is on f-droid!

**Comment by MAWSpitau** [comment]
Thanks!
