### ISSUE TITLE
Setup different times for specific exercises 

### ISSUE THREAD

**Issue by EdenDorf** [scoute-dich/Sieben#30]
Because i have a trainplan with where i need todo some of them longer.  Maybe procedural term of standard lenght. Or a way to increase and decrease specific exercises in m seconds.

**Comment by scoute-dich** [comment]
I think this would be also possible, but it's a lot of work. It would need more setting screens, perhaps a database and ... The goal of the app was to keep it simple...

**Comment by EdenDorf** [comment]
I like if it's simple use. But if it a nice piece of work you could hide deeper options to "experts "

Dont worry about all the ideas. I' good in thinking about something what to get "better" i would share my thoughts to you, because i liked it that much. And at this point this os the only help i can give :)

**Comment by scoute-dich** [comment]
I can implement this but it will take a little bit longer. It's on the agenda and added to milestone v2.0.

**Comment by scoute-dich** [comment]
Will be in next update.
