### ISSUE TITLE
Free adjustable time for exercises.

### ISSUE THREAD

**Issue by EdenDorf** [scoute-dich/Sieben#31]
I like how it works. But what if o want to train 70 second's? :) or only 15 becouse beginner with no fitness at all.

**Comment by scoute-dich** [comment]
see #29

**Comment by scoute-dich** [comment]
Something like this?
![screenshot_20170303-232104](https://cloud.githubusercontent.com/assets/3949944/23571211/40a5316a-0068-11e7-95f3-57e486adf448.png)

**Comment by EdenDorf** [comment]
There are some circleselections out. Maybe a better choice to setup minutes and seconds seperate. 

Or a second slider for minute's.  If you get better at your training you may think 2  minutes are a little short. 

But this is for sure a good improvement. 👍

**Comment by scoute-dich** [comment]
What are circleselections?

**Comment by EdenDorf** [comment]
don't know how there exactly named. Alarmdroid uses it for example. If i would struggle into of it what's openscource i would tell you.

At this point i would recommend to look into "meditation assistant" there are maybe some interesting features to imitate for you. For statistics and posting to community for example.

**Comment by scoute-dich** [comment]
Will adjustable from 15 - 120 seconds with next update. I think two minutes are enough, if not you can perform the workout again.
