### ISSUE TITLE
Endless training

### ISSUE THREAD

**Issue by EdenDorf** [scoute-dich/Sieben#32]
Maybe you could add a function where i get of all my chosen exercises a random trainplan. And it repeated endless. For some reason's its good not to follow ever the same interval. Your body know what's todo and the progress gets lowered. So i heard about it.

**Comment by scoute-dich** [comment]
see #30 

Many good ideas. But a lot of work. This is one of my first app. The code is not very good. So it would be a lot of work. But perhaps time by time, it ould be possible...

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
Also implemented with next update.
