### ISSUE TITLE
No Voice Commands

### ISSUE THREAD

**Issue by intuitiv-de** [scoute-dich/Sieben#36]
Hi,

I hear no voice commands, running the app on an Android 6 machine.
Any ideas?

Regards

**Comment by scoute-dich** [comment]
Here it works. Have you set up tts properly on your device and increased media volume? I know it sounds a bit silly, but sometimes the solution is simple...

**Comment by intuitiv-de** [comment]
Hi,

thanks a lot. I've deactivated a lot of the gogle stuff... Just re-installed tts and it works fine.
Thank You, the solution was simple...

**Comment by scoute-dich** [comment]
;-)
