### ISSUE TITLE
Detecting touch gestures for next/previous exercise

### ISSUE THREAD

**Issue by rsiccho** [scoute-dich/Sieben#4]
Hi,
At first, I love this app. Simple and straight forward.

Maybe you could detecting touch gestures for stepping to the next/previous exercise.
Opening the menu and hitting the small buttons is sometimes very hard. Especially when I don't wear my glasses.

On an other issue you mentioned, that you're not so familiar with developing. Here is a small example how it is working:
[http://stackoverflow.com/questions/13095494/how-to-detect-swipe-direction-between-left-right-and-up-down/](http://stackoverflow.com/questions/13095494/how-to-detect-swipe-direction-between-left-right-and-up-down/)

**Comment by scoute-dich** [comment]
Hi,

thanks for your suggestion. I found a solution. It will be implemented on version 1.3.

**Comment by scoute-dich** [comment]
Update is on f-droid!
