### ISSUE TITLE
Fix lint issues or disable specific warning/error 

### ISSUE THREAD

**Issue by krt16s** [scoute-dich/Sieben#7]
Current release does not build until `android { lintOptions { disable 'MissingTranslation' } }` is specified. Such modifications should be handled by upstream, since only you can know when it's okay to ignore lint issues.

**Comment by scoute-dich** [comment]
Hope it is fixed and will build properly...

**Comment by krt16s** [comment]
Indeed, fixed.

**Comment by krt16s** [comment]
Same issue again, see https://f-droid.org/wiki/page/de.baumann.sieben/lastbuild_15

**Comment by scoute-dich** [comment]
Ok,I added all missing translations...

**Comment by krt16s** [comment]
Thanks for the quickfix!
