### ISSUE TITLE
Change of page orientation restarts exercise

### ISSUE THREAD

**Issue by rsiccho** [scoute-dich/Sieben#8]
Hi,

Thanks for intoducing the gestures, it works like a charm.

I have another issue, while an exercise is running, my tablet changes sometimes the page orientation (portrait and landscape mode). This triggers a restart of the exercise. So it would be good, when the exercise continues with the same rest time.
By the way, actually there are two menu entries with help, I think the second should be labeled with "changelog"

**Comment by scoute-dich** [comment]
Hi,

I set screen orientation to portrait. "changelog"-string is also fixed (thanks for the hint).
At the moment I don't know how to implement that the countdown continues with the rest time. Android countdowntimer does not natively support pause and resume. There are some solutions on stackoverflow but at the moment I don't know how to implement them... 

If there are any suggestions, tell me.

**Comment by scoute-dich** [comment]
v1.4 is on his way...

**Comment by rsiccho** [comment]
Thank you, the solution prevents the restart.

**Comment by scoute-dich** [comment]
;-)
